apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoapachefre
spec:
  selector:
    matchLabels:
      app: argoapachefre
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      name: argoapachefre
      labels:
        app: argoapachefre
        tier: backend
        track: stable
    spec:
      containers:
      - image: httpd:2.4
        name: apache
        ports:
          - containerPort: 80