apiVersion: apps/v1
kind: Deployment
metadata:
  name: apachefre
spec:
  selector:
    matchLabels:
      app: apachefre
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      name: apachefre
      labels:
        app: apachefre
        tier: backend
        track: stable
    spec:
      containers:
      - image: httpd:2.4
        name: apache
        ports:
          - containerPort: 80